version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - nextjs_build:/app/.next

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - nextjs_build:/usr/share/nginx/html
    depends_on:
      - frontend

volumes:
  nextjs_build:
